esphome:
  name: humidity-sensor

esp8266:
  board: d1_mini

# Enable logging
logger:
  level: DEBUG

# Enable Home Assistant API
api:
  password: !secret api_password

ota:
  - platform: esphome
    password: !secret wifi_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  # Enable fallback hotspot (captive portal) in case wifi connection fails
  # ap:
  #   ssid: ""
  #   password: ""

# i2c:
#   sda: GPIO4
#   scl: GPIO5
#   scan: true

sensor:
  - platform: dht
    pin: D2 #D4 on shield
    temperature:
      name: "Living Room Temperature"
    humidity:
      name: "Living Room Humidity"
    update_interval: 60s

  # - platform: custom
  #   lambda: |-
  #     auto TMP_sensor = new TempSensor();
  #     App.register_component(TMP_sensor);
  #     return {TMP_sensor->temp_sensor, TMP_sensor->humid_sensor, TMP_sensor->heat_sensor};

  # sensors:
  #   - name: "Temperature"
  #     accuracy_decimals: 5
  #     unit_of_measurement: "°C"
  #   - name: "Heat Index"
  #     accuracy_decimals: 5
  #   - name: "Humidity"
  #     accuracy_decimals: 5
  #     unit_of_measurement: "%"
# deep_sleep:
#   run_duration: 45s
#   sleep_duration: 20min
