esphome:
  name: uv-sensor

esp8266:
  board: d1_mini

# Enable logging
logger:
  level: DEBUG

# Enable Home Assistant API
api:
  password: !secret api_password

ota:
  - platform: esphome
    password: !secret wifi_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  # Enable fallback hotspot (captive portal) in case wifi connection fails
  # ap:
  #   ssid: ""
  #   password: ""

# i2c:
#   sda: GPIO4
#   scl: GPIO5
#   scan: true

sensor:
#   run_duration: 45s
#   sleep_duration: 20min
