esphome:
  name: cover-lux-sensor

esp8266:
  board: d1_mini_lite

# Enable logging
logger:
  level: DEBUG

# Enable Home Assistant API
api:
  encryption:
    key: !secret api_key

ota:
  - platform: esphome
    password: !secret wifi_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

i2c:
  sda: D1
  scl: D2
  scan: true

sensor:
  - platform: bh1750
    name: 'Lichtstärke'
    address: 0x23
    update_interval: 5s

  - platform: adc
    pin: A0
    update_interval: 5s
    name: 'Batteriespannung'
    id: battery_voltage
    filters:
      - multiply: 5.4
    unit_of_measurement: 'V'

  - platform: template
    name: 'Batterieladung'
    update_interval: 5s
    unit_of_measurement: '%'
    lambda: |-
      float voltage = id(battery_voltage).state;
      const float max_voltage = 5.4;  // Maximum battery voltage
      const float min_voltage = 2.3;  // Minimum operational voltage
      float percentage = ((voltage - min_voltage) / (max_voltage - min_voltage)) * 100.0;

      if (percentage < 0.0) {
        return 0.0;
      } else if (percentage > 100.0) {
        return 100.0;
      } else {
        return percentage;
      }

deep_sleep:
  run_duration: 20s
  sleep_duration: 20min
  id: deep_sleep_control

time:
  - platform: homeassistant
    id: esptime
    on_time:
      - hours: 21
        then:
          - deep_sleep.enter:
              id: deep_sleep_control
              sleep_duration: 9h
